function showMenu(idRestaurant) {

    // เก็บค่าที่แถวที่ click ไป
    let _restaurant = dataTblRestaurant.find((item) => {
        return item.id == idRestaurant
    })

    $('#menu').empty()

    $('#menu').append($('<div></div>')
        .append($('<h3></h3>')
            .text(`${_restaurant.name}'s Menu`)
            .css('display', 'block')
        )
    )

    $('#menu').append($('<div></div>')
        .append('<label>Select Menu Type : </label>')
        .append($('<select id="sel"></select>')
            .append($('<option></option>')
                .attr('value', 0)
                .attr('selected', 'selected')
                .text('All')
            )
        )
    )

    $.each(dataLUTMenuType, function () {
        $('#sel').append($('<option></option>')
            .attr('value', this.id)
            .text(this.name))
    })

    $('#menu').append($('<div></div>')
        .append($('<table></table>')
            .addClass('table')
            .append($('<thead></thead>')
                .append($('<tr></tr>')
                    .addClass('bgBlue')
                    .css('color', 'white')
                    .append($('<th></th>')
                        .text('Name')
                    )
                    .append($('<th></th>')
                        .text('Type')
                    )
                    .append($('<th></th>')
                        .text('Price(Baht)')
                    )
                    .append($('<th></th>')
                        .text(' ')
                    )
                    .append($('<th></th>')
                        .text(' ')
                    )
                )
            )
            .append('<tbody id="dataMenu"></tbody>')
        )
    )

    $('#dataMenu').append($('<tr></tr>')
        .append($('<td></td>')
            .text('Name')
        )
        .append($('<td></td>')
            .text('Type')
        )
        .append($('<td></td>')
            .text('Price(Baht)')
        )
        .append($('<td></td>')
            .text(' ')
        )
        .append($('<td></td>')
            .text(' ')
        )
    )

}